name: drag_ball
description: A flutter package, inpiration Indonesian e-commerce widget or similiar AssistiveTouch on Iphone.
version: 0.0.3
homepage: https://github.com/farhanfadila1717/drag_ball
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
